sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  allow_failures:
    - php: 7.4snapshot

script:
  - ./vendor/bin/phpunit

before_install:
  - travis_retry composer self-update

install:
  - composer install
